<a href="https://colab.research.google.com/github/AI-fanatic24/machine-learning-foundations/blob/main/Mushroom_Classification_Edible_or_Poisonous.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix

In [ ]:
df = pd.read_csv('/content/mushrooms.csv')
df

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,e,k,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,b,c,l
8120,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,n,o,p,b,v,l
8121,e,f,s,n,f,n,a,c,b,n,...,s,o,o,p,o,o,p,b,c,l
8122,p,k,y,n,f,y,f,c,n,b,...,k,w,w,p,w,o,e,w,v,l
8123,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,o,c,l

In [ ]:
one_hot_features = ['cap-shape','cap-surface','cap-color','bruises','odor','gill-attachment','gill-spacing','gill-size','gill-color','stalk-shape','stalk-root','stalk-surface-above-ring','stalk-surface-below-ring','stalk-color-above-ring','stalk-color-below-ring','veil-type','veil-color','ring-number','ring-type','spore-print-color','population','habitat']

In [ ]:
df = pd.get_dummies(data=df,prefix=one_hot_features,columns=one_hot_features)

In [ ]:
df

,class,cap-shape_b,cap-shape_c,cap-shape_f,cap-shape_k,cap-shape_s,cap-shape_x,cap-surface_f,cap-surface_g,cap-surface_s,...,population_s,population_v,population_y,habitat_d,habitat_g,habitat_l,habitat_m,habitat_p,habitat_u,habitat_w
0,p,0,0,0,0,0,1,0,0,1,...,1,0,0,0,0,0,0,0,1,0
1,e,0,0,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
2,e,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
3,p,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
4,e,0,0,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,e,0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
8120,e,0,0,0,0,0,1,0,0,1,...,0,1,0,0,0,1,0,0,0,0
8121,e,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
8122,p,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
8123,e,0,0,0,0,0,1,0,0,1,...,0,0,0,0,0,1,0,0,0,0

In [ ]:
df.loc[df["class"] == "p","class"] = 0      # 0 = poisonous
df.loc[df["class"] == "e","class"] = 1      # 1 = edible

In [ ]:
df

,class,cap-shape_b,cap-shape_c,cap-shape_f,cap-shape_k,cap-shape_s,cap-shape_x,cap-surface_f,cap-surface_g,cap-surface_s,...,population_s,population_v,population_y,habitat_d,habitat_g,habitat_l,habitat_m,habitat_p,habitat_u,habitat_w
0,0,0,0,0,0,0,1,0,0,1,...,1,0,0,0,0,0,0,0,1,0
1,1,0,0,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
2,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
3,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
4,1,0,0,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,1,0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
8120,1,0,0,0,0,0,1,0,0,1,...,0,1,0,0,0,1,0,0,0,0
8121,1,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
8122,0,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
8123,1,0,0,0,0,0,1,0,0,1,...,0,0,0,0,0,1,0,0,0,0

In [ ]:
features = [x for x in df.columns if x not in ['class']]

In [ ]:
X_train,X_,y_train,y_ = train_test_split(df[features],df['class'],train_size=0.60,random_state=1)
X_val,X_test,y_val,y_test = train_test_split(X_,y_,train_size=0.50,random_state=1)
del X_,y_

In [ ]:
X_train = np.array(X_train,dtype='float32')
X_val = np.array(X_val,dtype='float32')
y_train = np.array(y_train,dtype='float32').reshape(-1,1)
y_val = np.array(y_val,dtype='float32').reshape(-1,1)
X_test = np.array(X_test,dtype='float32')
y_test = np.array(y_test,dtype='float32').reshape(-1,1)

In [ ]:
print("X_train.shape",X_train.shape)
print("y_train.shape",y_train.shape)
print("X_val.shape",X_val.shape)
print("y_val.shape",y_val.shape)
print("X_test.shape",X_test.shape)
print("y_test.shape",y_test.shape)

X_train.shape (4874, 117)
y_train.shape (4874, 1)
X_val.shape (1625, 117)
y_val.shape (1625, 1)
X_test.shape (1625, 117)
y_test.shape (1625, 1)

In [ ]:
xgb_model = XGBClassifier(n_estimators=200,learning_rate=0.2,verbosity=1,random_state=1)
xgb_model.fit(X_train,y_train,eval_set=[(X_val,y_val)],early_stopping_rounds=5)

[0]	validation_0-logloss:0.51438
[1]	validation_0-logloss:0.39461
[2]	validation_0-logloss:0.30869
[3]	validation_0-logloss:0.24472
[4]	validation_0-logloss:0.19593
[5]	validation_0-logloss:0.15811
[6]	validation_0-logloss:0.12844
[7]	validation_0-logloss:0.10491
[8]	validation_0-logloss:0.08567
[9]	validation_0-logloss:0.07024
[10]	validation_0-logloss:0.05784
[11]	validation_0-logloss:0.04778
[12]	validation_0-logloss:0.03932
[13]	validation_0-logloss:0.03247
[14]	validation_0-logloss:0.02685
[15]	validation_0-logloss:0.02228
[16]	validation_0-logloss:0.01864
[17]	validation_0-logloss:0.01557
[18]	validation_0-logloss:0.01312
[19]	validation_0-logloss:0.01121
[20]	validation_0-logloss:0.00968
[21]	validation_0-logloss:0.00834
[22]	validation_0-logloss:0.00722
[23]	validation_0-logloss:0.00627
[24]	validation_0-logloss:0.00548
[25]	validation_0-logloss:0.00483
[26]	validation_0-logloss:0.00434
[27]	validation_0-logloss:0.00386
[28]	validation_0-logloss:0.00354
[29]	validation_0-logloss:0.00322
[30]	validation_0-logloss:0.00300
[31]	validation_0-logloss:0.00274
[32]	validation_0-logloss:0.00256
[33]	validation_0-logloss:0.00237
[34]	validation_0-logloss:0.00221
[35]	validation_0-logloss:0.00208
[36]	validation_0-logloss:0.00200
[37]	validation_0-logloss:0.00189
[38]	validation_0-logloss:0.00183
[39]	validation_0-logloss:0.00175
[40]	validation_0-logloss:0.00165
[41]	validation_0-logloss:0.00161
[42]	validation_0-logloss:0.00156
[43]	validation_0-logloss:0.00148
[44]	validation_0-logloss:0.00144
[45]	validation_0-logloss:0.00141
[46]	validation_0-logloss:0.00140
[47]	validation_0-logloss:0.00135
[48]	validation_0-logloss:0.00134
[49]	validation_0-logloss:0.00131
[50]	validation_0-logloss:0.00130
[51]	validation_0-logloss:0.00128
[52]	validation_0-logloss:0.00124
[53]	validation_0-logloss:0.00121
[54]	validation_0-logloss:0.00120
[55]	validation_0-logloss:0.00117
[56]	validation_0-logloss:0.00115
[57]	validation_0-logloss:0.00115
[58]	validation_0-logloss:0.00112
[59]	validation_0-logloss:0.00110
[60]	validation_0-logloss:0.00109
[61]	validation_0-logloss:0.00107
[62]	validation_0-logloss:0.00105
[63]	validation_0-logloss:0.00104
[64]	validation_0-logloss:0.00102
[65]	validation_0-logloss:0.00102
[66]	validation_0-logloss:0.00100
[67]	validation_0-logloss:0.00099
[68]	validation_0-logloss:0.00098
[69]	validation_0-logloss:0.00097
[70]	validation_0-logloss:0.00096
[71]	validation_0-logloss:0.00095
[72]	validation_0-logloss:0.00094
[73]	validation_0-logloss:0.00093
[74]	validation_0-logloss:0.00093
[75]	validation_0-logloss:0.00092
[76]	validation_0-logloss:0.00092
[77]	validation_0-logloss:0.00091
[78]	validation_0-logloss:0.00090
[79]	validation_0-logloss:0.00090
[80]	validation_0-logloss:0.00089
[81]	validation_0-logloss:0.00089
[82]	validation_0-logloss:0.00088
[83]	validation_0-logloss:0.00088
[84]	validation_0-logloss:0.00088
[85]	validation_0-logloss:0.00087
[86]	validation_0-logloss:0.00087
[87]	validation_0-logloss:0.00086
[88]	validation_0-logloss:0.00086
[89]	validation_0-logloss:0.00086
[90]	validation_0-logloss:0.00085
[91]	validation_0-logloss:0.00085
[92]	validation_0-logloss:0.00084
[93]	validation_0-logloss:0.00084
[94]	validation_0-logloss:0.00084
[95]	validation_0-logloss:0.00083
[96]	validation_0-logloss:0.00083
[97]	validation_0-logloss:0.00083
[98]	validation_0-logloss:0.00082
[99]	validation_0-logloss:0.00082
[100]	validation_0-logloss:0.00082
[101]	validation_0-logloss:0.00082
[102]	validation_0-logloss:0.00082
[103]	validation_0-logloss:0.00081
[104]	validation_0-logloss:0.00081
[105]	validation_0-logloss:0.00081
[106]	validation_0-logloss:0.00081
[107]	validation_0-logloss:0.00081
[108]	validation_0-logloss:0.00080
[109]	validation_0-logloss:0.00080
[110]	validation_0-logloss:0.00080
[111]	validation_0-logloss:0.00080
[112]	validation_0-logloss:0.00080
[113]	validation_0-logloss:0.00080
[114]	validation_0-logloss:0.00080
[115]	validation_0-logloss:0.00080
[116]	validation_0-logloss:0.00079
[117]	validation_0-logloss:0.00079
[118]	validation_0-logloss:0.00079
[119]	validation_0-logloss:0.00079
[120]	validation_0-logloss:0.00079
[121]	validation_0-logloss:0.00079
[122]	validation_0-logloss:0.00079
[123]	validation_0-logloss:0.00078
[124]	validation_0-logloss:0.00078
[125]	validation_0-logloss:0.00078
[126]	validation_0-logloss:0.00078
[127]	validation_0-logloss:0.00078
[128]	validation_0-logloss:0.00078
[129]	validation_0-logloss:0.00078
[130]	validation_0-logloss:0.00078
[131]	validation_0-logloss:0.00078
[132]	validation_0-logloss:0.00078
[133]	validation_0-logloss:0.00077
[134]	validation_0-logloss:0.00077
[135]	validation_0-logloss:0.00077
[136]	validation_0-logloss:0.00077
[137]	validation_0-logloss:0.00077
[138]	validation_0-logloss:0.00077
[139]	validation_0-logloss:0.00077
[140]	validation_0-logloss:0.00077
[141]	validation_0-logloss:0.00077
[142]	validation_0-logloss:0.00077
[143]	validation_0-logloss:0.00077
[144]	validation_0-logloss:0.00077
[145]	validation_0-logloss:0.00077
[146]	validation_0-logloss:0.00077
[147]	validation_0-logloss:0.00077
[148]	validation_0-logloss:0.00077
[149]	validation_0-logloss:0.00077
[150]	validation_0-logloss:0.00077
[151]	validation_0-logloss:0.00077
[152]	validation_0-logloss:0.00077
[153]	validation_0-logloss:0.00076
[154]	validation_0-logloss:0.00076
[155]	validation_0-logloss:0.00077
[156]	validation_0-logloss:0.00076
[157]	validation_0-logloss:0.00076
[158]	validation_0-logloss:0.00076
[159]	validation_0-logloss:0.00076
[160]	validation_0-logloss:0.00076
[161]	validation_0-logloss:0.00076
[162]	validation_0-logloss:0.00076
[163]	validation_0-logloss:0.00076
[164]	validation_0-logloss:0.00076
[165]	validation_0-logloss:0.00076
[166]	validation_0-logloss:0.00076
[167]	validation_0-logloss:0.00076
[168]	validation_0-logloss:0.00076
[169]	validation_0-logloss:0.00076
[170]	validation_0-logloss:0.00076
[171]	validation_0-logloss:0.00076
[172]	validation_0-logloss:0.00076
[173]	validation_0-logloss:0.00076
[174]	validation_0-logloss:0.00076
[175]	validation_0-logloss:0.00076
[176]	validation_0-logloss:0.00076
[177]	validation_0-logloss:0.00076
[178]	validation_0-logloss:0.00076
[179]	validation_0-logloss:0.00076
[180]	validation_0-logloss:0.00076
[181]	validation_0-logloss:0.00076
[182]	validation_0-logloss:0.00076
[183]	validation_0-logloss:0.00076
[184]	validation_0-logloss:0.00075
[185]	validation_0-logloss:0.00075
[186]	validation_0-logloss:0.00075
[187]	validation_0-logloss:0.00075
[188]	validation_0-logloss:0.00075
[189]	validation_0-logloss:0.00075
[190]	validation_0-logloss:0.00075
[191]	validation_0-logloss:0.00075
[192]	validation_0-logloss:0.00075
[193]	validation_0-logloss:0.00075
[194]	validation_0-logloss:0.00075
[195]	validation_0-logloss:0.00075
[196]	validation_0-logloss:0.00075
[197]	validation_0-logloss:0.00075
[198]	validation_0-logloss:0.00075
[199]	validation_0-logloss:0.00075

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.2, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, random_state=1, ...)

In [ ]:
xgb_model.best_iteration

199

In [ ]:
print("Train accuracy: ",accuracy_score(xgb_model.predict(X_train),y_train))
print("Validation accuracy: ",accuracy_score(xgb_model.predict(X_val),y_val))
print("Test accuracy: ",accuracy_score(xgb_model.predict(X_test),y_test))

Train accuracy:  1.0
Validation accuracy:  1.0
Test accuracy:  1.0

In [ ]:
train_pred = xgb_model.predict(X_train)
val_pred = xgb_model.predict(X_val)
test_pred = xgb_model.predict(X_test)

In [ ]:
print("Train Confusion Matrix:\n",confusion_matrix(y_train,train_pred))
print("Validation Confusion Matrix:\n",confusion_matrix(y_val,val_pred))
print("Test Confusion Matrix:\n",confusion_matrix(y_test,test_pred))

Train Confusion Matrix:
 [[2336    0]
 [   0 2538]]
Validation Confusion Matrix:
 [[782   0]
 [  0 843]]
Test Confusion Matrix:
 [[798   0]
 [  0 827]]

In [ ]:
for i in range(200):
  print("Prediction: ",test_pred[i],"  Actual Value: ",int(y_test[i]))

Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1